# nome = str(input('Qual e o seu nome completo?'))
# frase1 = nome.upper()
# frase2 = nome.casefold()
# frase3 = len(nome)
# frase4 = len(nome[:5])
# frase5 = nome[:5]
# print('analisando o seu nome...')
# print(f'seu nome em letras maiusculas e {frase1}')
# print(f'seu nome em letras minusculas e {frase2}')
# print(f'seu nome tem ao todo {frase3} letras ')
# print(f'seu nome {frase5} e tem {frase4} letras')

nome = str(input('Qual e seu nome completo:')).strip()
separa = nome.split()
print('Analisando o seu nome....')
print('O seu nome com letras maiusculas e {}'.format(nome.upper()))
print('O seu nome com letras minusculas e {}'.format(nome.casefold()))
print('Seu nome tem {} letras '.format(len(nome) - nome.count(' ')))
print('meu nome e {} e tem {} letras'.format(separa[0], len(separa[0])))
